"""empty message

Revision ID: 780f0cc40ea9
Revises: 28be40ee4953
Create Date: 2021-03-19 00:28:18.865415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780f0cc40ea9'
down_revision = '28be40ee4953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('new_properties', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('new_properties', 'name')
    # ### end Alembic commands ###
