"""empty message

Revision ID: cb663bc5a304
Revises: dd0974fcbfd2
Create Date: 2021-03-22 21:30:13.092894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb663bc5a304'
down_revision = 'dd0974fcbfd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('new_properties_property_title_key', 'new_properties', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('new_properties_property_title_key', 'new_properties', ['property_title'])
    # ### end Alembic commands ###
